package models

import (
	"time"

	"github.com/amirhnajafiz/bedrock-api/pkg/enums"
)

// Session represents the client's requests.
type Session struct {
	// Id is the unique identifier for the session, generated by the server.
	Id string `json:"id"`
	// DockerDId is the identifier of the Docker Daemon associated with the session, generated by the server.
	DockerDId string `json:"dockerd_id"`
	// CreatedAt is the timestamp when the session was created, generated by the server.
	CreatedAt time.Time `json:"created_at"`
	// DeletedAt is the timestamp when the session was deleted, generated by the server.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Status indicates the current status of the session, generated by the server.
	Status enums.SessionStatus `json:"status"`
	// Spec holds the user request details, provided by the client.
	Spec Spec `json:"spec"`
}

// Spec field of the session holds the user request.
type Spec struct {
	// Image is the Docker image to be used for the session, provided by the client.
	Image string `json:"image"`
	// Command is the command to be executed in the Docker container, provided by the client.
	Command string `json:"command"`
	// TTL is the time-to-live for the session, provided by the client.
	TTL time.Duration `json:"ttl"`
}
